server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-registration
    username: postgres
    password: Prasanna@123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
